services:
  adt-portal-adminlte:
    image: nginx:stable-alpine
    container_name: adt-portal-adminlte
    restart: unless-stopped

    expose:
      - "80"
    #ports:
    #- "8087:80"

    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      APP_ENV: ${APP_ENV:-qa}

    volumes:
      - ./public:/app/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    command: >
      /bin/sh -c "
      mkdir -p /usr/share/nginx/html &&
      cp -r /app/public/. /usr/share/nginx/html/ &&
      envsubst < /app/public/assets/js/config.template.js > /usr/share/nginx/html/assets/js/config.js &&
      nginx -g 'daemon off;'
      "

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/login.html"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s